FrenchTB/FrenchTB/urls.py
from django.contrib import admin
from django.urls import path
from ftb.views import main, backstage, authentication

urlpatterns = [
    path('admin/', admin.site.urls),

    # 主页
    path('index/', main.index, name='主页'),
    path('index_old/', main.index_old, name='主页'),

    # 登录注册
    path('login/', authentication.login, name='登录'),
    path('signup/', authentication.signup, name='注册'),
    path('logout/', authentication.logout),
    path('image/code/', authentication.image_code),

    # 后台管理

    # 词库管理
    path('backstage/term/', backstage.term),
    path('backstage/term/add/', backstage.term_add),

]

FrenchTB/ftb/models.py
from django.db import models
"""
python manage.py makemigrations
python manage.py migrate
"""
class Term(models.Model):
    """ 术语 """
    chinese = models.TextField(verbose_name="中文")
    french = models.TextField(verbose_name="法语")
    similar = models.TextField(verbose_name="类似表达")
    source = models.CharField(verbose_name="来源", max_length=128)
    definition = models.TextField(verbose_name="定义")
    example = models.TextField(verbose_name="例句")
    cata_choices = (
        (1, "其他词汇"),
        (2, "决策部署"),
        (3, "防控救治"),
        (4, "专有名词"),
        (5, "机构场所"),
        (6, "社会生活"),
    )
    cata = models.SmallIntegerField(verbose_name="分类", choices=cata_choices)
    tag = models.CharField(verbose_name="标签", max_length=32)

class Account(models.Model):
    """ 账号 """
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)
    email = models.EmailField(verbose_name="邮箱", blank=True, null=True)
    phone = models.CharField(verbose_name="手机号", max_length=11, blank=True, null=True)
    role_choices = (
        (1, "普通用户"),
        (2, "管理员"),
    )
    role = models.SmallIntegerField(verbose_name="角色", choices=role_choices)
    create_time = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    sex_choices = (
        (1, "男"),
        (2, "女"),
    )
    sex = models.SmallIntegerField(verbose_name="性别", choices=sex_choices, blank=True, null=True)
    age = models.SmallIntegerField(verbose_name="年龄", blank=True, null=True)

class Feedback(models.Model):
    """ 反馈 """
    title = models.CharField(verbose_name="反馈标题", max_length=128)
    content = models.TextField(verbose_name="反馈内容")
    create_time = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    account = models.ForeignKey(verbose_name="用户", to="Account", to_field="id", on_delete=models.CASCADE)

class Collection(models.Model):
    """ 收藏 """
    create_time = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    account = models.ForeignKey(verbose_name="用户", to="Account", to_field="id", on_delete=models.CASCADE)
    term = models.ForeignKey(verbose_name="术语", to="Term", to_field="id", on_delete=models.CASCADE)

class Notification(models.Model):
    """ 通知 """
    title = models.CharField(verbose_name="通知标题", max_length=128)
    content = models.TextField(verbose_name="通知内容")
    create_time = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    account = models.ForeignKey(verbose_name="用户", to="Account", to_field="id", on_delete=models.CASCADE)

class History(models.Model):
    """ 历史记录 """
    create_time = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    account = models.ForeignKey(verbose_name="用户", to="Account", to_field="id", on_delete=models.CASCADE)
    term = models.ForeignKey(verbose_name="术语", to="Term", to_field="id", on_delete=models.CASCADE)

FrenchTB/ftb/views/authentication.py
from django.shortcuts import render, redirect, HttpResponse
from django import forms
from io import BytesIO
from django.core.exceptions import ValidationError
from datetime import datetime

from ftb import models
from ftb.utils.encrypt import md5
from ftb.utils.code import check_code
from ftb.utils.Bootstrap import BootstrapModelForm

class LoginForm(forms.Form):

    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput(attrs={"class": 'form-control', 
                                      "id": 'floatingInput', 
                                      "placeholder": 'Username',
                                      "type": "username"}),
        required=True  # 不能为空
    )
    password = forms.CharField(
        label="密码",
        # render_value=True 为不清空密码框
        widget=forms.PasswordInput(attrs={"class": 'form-control', 
                                          "id": 'floatingPassword', 
                                          "placeholder": 'Password'}, render_value=True),
        required=True  # 不能为空
    )
    code = forms.CharField(
        label="验证码",
        widget=forms.TextInput(attrs={"class": 'form-control', 
                                      "placeholder": '验证码',
                                      "type": "imagecode"}),
        required=True  # 不能为空
    )

    def clean_password(self):
        orig_pwd = self.cleaned_data.get('password')
        return md5(orig_pwd)

def login(request):
    """ 登录 """

    if request.method == "GET":
        form = LoginForm()
        return render(request, 'login.html', {'form': form})
    
    form = LoginForm(data=request.POST)
    if form.is_valid():
        # 验证成功，获取到用户名和密码（form.cleaned_data）
        # print(form.cleaned_data)

        # * 验证码验证
        # pop() 用于及时清除 cleaned_data 中的验证码字段，防止后面用户名密码在数据库校验时出问题
        user_input_code = form.cleaned_data.pop('code')
        # 获取验证码或者空字符
        code = request.session.get('image_code', "")
        # 默认大写化
        if code.upper() != user_input_code.upper():
            form.add_error("code", "验证码错误")
            return render(request, 'login.html', {'form': form})

        # * 去数据库校验用户名和密码是否正确
        # 用解包的方式传字典进行验证（前提是 cleaned_data 字典里的键（即 LoginForm 里定义的字段名）要和数据库里（models.py）的字段相匹配）
        account_object = models.Account.objects.filter(**form.cleaned_data).first()
        # account_object = models.Account.objects.filter(username=form.cleaned_data['username'], password=form.cleaned_data['password']).first()
        if not account_object:
            form.add_error("password", "用户名或密码错误")  # 添加新报错到 form 里并显示在字段 password 上
            # form.add_error("username", "用户名或密码错误")  # 添加新报错到 form 里并显示在字段 username 上
            return render(request, 'login.html', {'form': form})

        # 用户名和密码正确
        # 网站生成随机字符串（这里是用户的 id 和用户名合在一起的字典）；写到用户浏览器的 cookie 中；再写入到 session 中
        # 可在浏览器开发人员工具中查到 cookie 中加密过的 session info；在数据库中可以查到对应的内容
        request.session["info"] = {'id': account_object.id, 'username': account_object.username}
        # 登录成功后给 session 设置 7 天超时
        request.session.set_expiry(60 * 60 * 24 * 7)
        return redirect("/index/")
    return render(request, 'login.html', {'form': form})

class SignupForm(BootstrapModelForm):

    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput(attrs={"class": 'form-control', 
                                      "id": 'floatingInput', 
                                      "placeholder": 'Username',
                                      "type": "username"}),
        required=True  # 不能为空
    )
    password = forms.CharField(
        label="密码",
        # render_value=True 为不清空密码框
        widget=forms.PasswordInput(attrs={"class": 'form-control', 
                                          "id": 'floatingPassword', 
                                          "placeholder": 'Password'}, render_value=True),
        required=True  # 不能为空
    )
    # 单独添加“确认密码”
    confirm_password = forms.CharField(
        label="确认密码",
        widget=forms.PasswordInput(attrs={"class": 'form-control', 
                                          "id": 'floatingConfirmPassword', 
                                          "placeholder": 'ConfirmPassword',
                                          "type": 'confirmpassword'}),

        # （render_value）验证错误后不清空输入框
        # widget=forms.PasswordInput(render_value=True)
        )
    
    class Meta:
        model = models.Account
        fields = ["username", "password", "confirm_password"]
    
    # 调用 encrypt.py 执行 md5 加密
    def clean_password(self):
        orig_pwd = self.cleaned_data.get('password')
        return md5(orig_pwd)

    # 验证确认密码的清理方法，参考下面文档
    # https://docs.djangoproject.com/zh-hans/4.1/ref/forms/validation/
    # clean_xxx 其中xxx为要验证并保存的字段
    def clean_confirm_password(self):
        # print(self.cleaned_data)
        orig_pwd = self.cleaned_data.get('password')
        conf_pwd = md5(self.cleaned_data.get('confirm_password'))
        # print(self.cleaned_data)
        # print(orig_pwd, conf_pwd)
        if conf_pwd != orig_pwd:
            raise ValidationError("密码不一致，请重新输入")
        return conf_pwd  # 返回什么，该字段保存到数据库的值就是什么（进入 form）
    
def signup(request):
    if request.method == 'GET':
        
        form = SignupForm()
        return render(request, "signup.html", {
            "form": form,
            })
    
    # 获取用户 POST 提交过来的数据，并进行数据校验
    form = SignupForm(data=request.POST)
    if form.is_valid():  # 逐一对 UserModelForm 内的字段进行校验
        # * 去数据库校验用户名和密码是否正确
        # 用解包的方式传字典进行验证（前提是 cleaned_data 字典里的键（即 LoginForm 里定义的字段名）要和数据库里（models.py）的字段相匹配）
        account_object = models.Account.objects.filter(username=form.cleaned_data['username']).first()
        # account_object = models.Account.objects.filter(username=form.cleaned_data['username'], password=form.cleaned_data['password']).first()
        if account_object:
            form.add_error("username", "当前用户名已注册")  # 添加新报错到 form 里并显示在字段 username 上
            return render(request, 'signup.html', {'form': form})
        # 数据合法
        # print(form.cleaned_data)
        # 保存到数据库 UserInfo（UserModelForm 内 Meta 定义的数据库表）
        form.instance.role = 1  # 为新注册用户设置默认角色为普通用户
        form.save()  # save() 为添加数据，非 update，此处添加数据和后面的修改数据实现方法有出入
        return redirect("/login/")
    return render(request, "signup.html", {
            "form": form,
            })

def image_code(request):
    """ 生成图片验证码 """

    # 创建图片对象
    img, code_string = check_code()
    # print(code_string)

    # 将验证码字符串写入到 session 中（以便后续获取验证码再进行校验）
    request.session['image_code'] = code_string
    # 给 session 设置 60s 超时
    request.session.set_expiry(60)

    # 写入内存
    stream = BytesIO()
    img.save(stream, 'png')
    
    return HttpResponse(stream.getvalue())

def logout(request):
    """ 注销 """

    request.session.clear()
    return redirect('/login/')

FrenchTB/ftb/views/backstage.py
from django.shortcuts import render, redirect, HttpResponse
import json
import random
from datetime import datetime
from django.shortcuts import render, redirect, HttpResponse
from django.http import JsonResponse
from django import forms
from django.core.exceptions import ValidationError
from django.views.decorators.csrf import csrf_exempt

from ftb import models
from ftb.utils.pagination import Pagination
from ftb.utils.Bootstrap import BootstrapModelForm
class TermModelForm(BootstrapModelForm):
    class Meta:
        model = models.Term
        # fields = "__all__"
        fields = ["chinese", "french", "similar", "source", "definition", "example", "cata", "tag"]


def term(request):
    """ 词库 """

    form = TermModelForm()

    # 关键词检索功能
    # 创建一个空字典（默认搜索关键词为空）
    data_dict = {}
    search_data = request.GET.get('q','')  # 搜索框默认值预览，有值取q，没值取空字符串
    if search_data:
        data_dict["chinese__contains"] = search_data  # xxx__contains 的xxx为检索列头

    term_table = models.Term.objects.filter(**data_dict).all().order_by('-id')

    # 分页
    page_object = Pagination(request, term_table)
    page_queryset = page_object.page_queryset

    return render(request, "term.html" ,{
            'active_menu': 'term',                 #
            'data_table': page_queryset,                 #
            "page_string": page_object.pageCounting(),   # 页码
            'search_data' : search_data,                 # 检索数据
            'form': form,
            })


def term_add(request):
    """ 词库添加 """

    form = TermModelForm()
    if request.method == 'GET':
        
        form = TermModelForm()
        return render(request, "form_edit_template.html", {
            'active_menu': 'term',
            "form": form,
            })
    
    if request.method == "POST":
        # 获取用户 POST 提交过来的数据，并进行数据校验
        form = TermModelForm(data=request.POST)
        if form.is_valid():  # 逐一对 UserModelForm 内的字段进行校验
            # 数据合法
            # print(form.cleaned_data)
            # 保存到数据库 UserInfo（UserModelForm 内 Meta 定义的数据库表）
            form.save()  # save() 为添加数据，非 update，此处添加数据和后面的修改数据实现方法有出入
            return redirect("/backstage/term/")
        return render(request, "form_edit_template.html", {
                "form": form,
                })

FrenchTB/ftb/templates/account.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="static/plugins/bootstrap-3.4.1/css/bootstrap.css">
    <link rel="stylesheet" href="static/plugins/font-awesome-4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="static/css/index.css">
    <link rel="stylesheet" href="static/css/pattern.css">
    <link rel="stylesheet" href="static/css/component.css">
    <link rel="stylesheet" href="static/css/register.css">

</head>
<body>
  <div class="container">
    <!-- ***账号面板 -->
    <div class="account">

      <!-- **账户面板框架 -->
      <div class="account-board bg-blur">

        <!-- *欢迎页面板 -->
        <div class="welcome-mask">

          <!-- 欢迎页面板块 -->
          <div class="welcome-musk-panel">

            <!-- 欢迎页内容 -->
            <div class="content-sheet">

              <!-- 左侧登录欢迎页 -->
              <div class="sheet-panel">
                  <section class="sheet-title">
                      <span style="font-size: 32px; font-weight: bold;">欢迎来到<br>法语术语库</span>
                      
                  </section>
                  <section class="sheet-img">
                      <span>
                          <svg width="194" height="313" viewBox="0 0 194 313" fill="none" xmlns="http://www.w3.org/2000/svg">
                              <path fill-rule="evenodd" clip-rule="evenodd" d="M163.152 247.72C174.151 265.756 184.509 282.744 191.554 305.97C192.319 308.492 190.404 311 187.768 311H161.32C159.436 311 157.816 309.682 157.357 307.855C149.241 275.552 125.287 252.143 97 252.143C68.7129 252.143 44.759 275.552 36.6429 307.855C36.1838 309.682 34.5639 311 32.6796 311H6.23219C3.59617 311 1.68057 308.492 2.44571 305.97C9.49053 282.744 19.8494 265.756 30.8476 247.72C50.7626 215.06 72.7737 178.963 81 96.1714V32.3631C81 31.7484 80.8583 31.1419 80.5859 30.5908L77.0505 23.4378C76.7781 22.8867 76.6364 22.2802 76.6364 21.6654V18.8413C76.6364 17.5115 77.2973 16.2686 78.3998 15.525L84.3499 11.5123C85.0106 11.0666 85.7894 10.8286 86.5864 10.8286H90.0909C92.3001 10.8286 94.0909 9.03771 94.0909 6.82857V4.90909C94.0909 3.30244 95.3934 2 97 2V2C98.6067 2 99.9091 3.30244 99.9091 4.90909V6.82857C99.9091 9.03771 101.7 10.8286 103.909 10.8286H107.414C108.211 10.8286 108.989 11.0666 109.65 11.5123L115.6 15.525C116.703 16.2686 117.364 17.5115 117.364 18.8413V21.6654C117.364 22.2802 117.222 22.8867 116.95 23.4378L113.414 30.5908C113.142 31.1419 113 31.7484 113 32.3631V96.1714C121.226 178.963 143.237 215.06 163.152 247.72ZM80.7506 194.852L78.1589 207.305C76.1107 217.147 75.0866 222.068 77.7062 225.334C80.3257 228.6 85.2968 228.6 95.2391 228.6H98.7609C108.703 228.6 113.674 228.6 116.294 225.334C118.913 222.068 117.889 217.147 115.841 207.305L113.249 194.852C111.991 188.803 111.361 185.779 109.328 183.871C109.045 183.605 108.745 183.359 108.43 183.134C106.166 181.514 103.11 181.514 97 181.514C90.8896 181.514 87.8344 181.514 85.5699 183.134C85.2547 183.359 84.9547 183.605 84.6718 183.871C82.6388 185.779 82.0094 188.803 80.7506 194.852Z" stroke="#2F80ED" stroke-width="4"/>
                              </svg>
                      </span>
                  </section>
                  <section class="sheet-link">
                      <span>还没有账户？</span>
                      <button type="button" class="btn-m-sub" id="account-register-btn">注册</button>
                  </section>
              </div><!-- 左侧登录欢迎页 -->

              <!-- 右注册欢迎页 -->
              <div class="sheet-panel">
                  <section class="sheet-title">
                      <span style="font-size: 32px; font-weight: bold;">欢迎来到<br>法语术语库</span>
                      
                  </section>
                  <section class="sheet-img">
                      <span>
                          <svg width="256" height="216" viewBox="0 0 256 216" fill="none" xmlns="http://www.w3.org/2000/svg">
                              <path d="M87.5 115.632V210C87.5 212.209 85.7091 214 83.5 214L6 214C3.79086 214 2 212.209 2 210V6C2 3.79086 3.79086 2 6 2H250C252.209 2 254 3.79086 254 6V210C254 212.209 252.209 214 250 214L172.5 214C170.291 214 168.5 212.209 168.5 210V115.632C168.5 105.089 164.233 94.9788 156.638 87.5242C140.822 72.0009 115.178 72.0009 99.3622 87.5242C91.767 94.9788 87.5 105.089 87.5 115.632Z" stroke="#EB5757" stroke-width="4"/>
                              </svg>                                                
                      </span>
                  </section>
                  <section class="sheet-link">
                      <span>已经有账户？</span>
                      <button type="button" class="btn-m btn-red-sub" id="account-login-btn">登录</button>
                  </section>
              </div><!-- 右注册欢迎页 -->

            </div><!-- 欢迎页内容 -->
              
          </div><!-- 欢迎页面板块 -->

        </div><!-- 欢迎页面板 -->
          
        <!-- *注册面板 -->
        <div class="side-panel" id="right">

          <!-- 注册面板标题 -->
          <section class="side-panel-title">
            <span style="font-size: 32px; font-weight: bold;">注册</span>
          </section>

          <!-- 注册面板表单 -->
          <form method="post" class="side-panel-form" action="#">
            <ul>
                <li>
                    <label class="input-placeholder">用户名</label>
                    <input type="text" autocomplete="username" name="user">
                </li>
                <li>
                    <label class="input-placeholder">邮箱</label>
                    <input type="email" autocomplete="email" name="email" placeholder="邮箱">
                </li>
                <li>
                    <label class="input-placeholder">密码</label>
                    <input type="password" autocomplete="current-password" name="pwd" placeholder="密码">
                </li>
                <li>
                    <label class="input-placeholder">确认密码</label>
                    <input type="password" autocomplete="new-password" placeholder="确认密码">
                </li>
            </ul>

            <!-- 注册面板按钮 -->
            <section class="side-panel-btn-wrap">
              <input type="submit" class="btn-l btn-red" value="注册">
            </section>

          </form>
        </div><!-- 注册面板 -->

        <!-- *登录面板 -->
        <div class="side-panel" id="left">

          <!-- 登录面板标题 -->
          <section class="side-panel-title">
            <span style="font-size: 32px; font-weight: bold;">登录</span>
          </section>

          <!-- 登录面板表单 -->
          <form method="post" class="side-panel-form" action="#">
              <ul>
                  <li>
                      <label class="input-placeholder">用户名</label>
                      <input type="text" autocomplete="username" name="user">
                  <li>
                      <label class="input-placeholder">密码</label>
                      <input type="password" autocomplete="current-password" name="pwd" placeholder="密码">
                  </li>
              </ul>

              <!-- 登录面板按钮 -->
              <div class="side-panel-btn-wrap">
                  <input type="submit" class="btn-l" value="登录">
              </div>

          </form>

      </div><!-- 登录面板 -->

    </div><!-- 账号面板 -->
  </div>

  

  <script src="static/plugins/jQuery/jquery.min.js"></script>
  <script src="static/plugins/bootstrap-3.4.1/js/bootstrap.js"></script>
  <script src="static/js/index.js"></script>
  <script src="static/js/register.js"></script>
  

</body>
</html>

FrenchTB/ftb/templates/form_edit_template.html
{% extends "backstage_template.html" %}
{% load static %}
{% block title %}
词库管理 | 法语在线术语库
{% endblock %}

{% block css %}

<style>
    .input-group>.form-control, 
    .input-group>.form-select {
        position: relative;
        flex: 1 1 auto;
        flex-direction: column;
        width: 100%;
        height: 100px;
        min-width: 0;
    }
  </style>

{% endblock %}

{% block content %}
<div class="d-flex flex-column justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">

  <section class="w-100">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        你目前所在：
        <!-- <li class="breadcrumb-item"><a href="#">Library</a></li> -->
        <li class="breadcrumb-item active" aria-current="page">词库管理</li>
      </ol>
    </nav>
  </section>

  <section class="w-100">
    
    <form method="post" novalidate>
        {% csrf_token %}
        
        <div class="row">
            {% for field in form %}
            <div class="col-6">
                <div class="input-group mb-3" style="position: relative;">
                    <label for="{{ field.name }}" class="form-label">{{ field.label }}</label>
                    {{ field }}
                    <span style="color: red;">{{ field.errors.0 }}</span>
                </div>
            </div>
            {% endfor %}
        </div>

        <button type="submit" class="btn btn-primary">保存</button>
        
    </form>
  </section>

  
</div>




  {% endblock %}

  {% block js %}
  

 


                                    
            
</script>
  {% endblock %}

FrenchTB/ftb/templates/term.html
{% extends "backstage_template.html" %}
{% load static %}
{% block title %}
词库管理 | 法语在线术语库
{% endblock %}

{% block css %}
<style>
  thead {
    
    white-space: nowrap;
  }
  thead tr th {
    z-index: 3; 
    position: sticky;
    min-width: 80px;
    top: 0;
    /* border-bottom: 4px solid rgb(59, 59, 59); */
  }
  /* 右侧操作栏冻结 */
  table thead tr th:last-child{
    /* display: block; */
    z-index: 4;
    position: sticky;
    top: 0;
    right: 0;
    /* box-shadow: 0 0 10px rgba(0, 0, 0, 0.178); */
  }
  table tbody tr td:last-child {
    display: block;
    background-color: rgb(255, 255, 255);
    /* z-index: 3; */
    position: sticky;
    right: 0;
    /* box-shadow: 0 4px 10px rgba(0, 0, 0, 0.178); */
  }
</style>


{% endblock %}

{% block content %}
<div class="d-flex flex-column justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">

  <section class="w-100">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        你目前所在：
        <!-- <li class="breadcrumb-item"><a href="#">Library</a></li> -->
        <li class="breadcrumb-item active" aria-current="page">词库管理</li>
      </ol>
    </nav>
  </section>

  <section class="w-100">
    <!-- 功能面板-新建-搜索 -->
    <div>
      <!-- 按钮-新建词条 -->
      <a class="btn btn-success btn-primary" href="/backstage/term/add/">
        <i class="bi bi-plus"></i>新建词条</a>
      <!-- 组件-搜索组件 -->
      <form class="input-group mb-3" method="get" style="float: right; width: 30%;" role="search">

        <input type="text" class="form-control" placeholder="搜索词条" name="q" value="{{ search_data }}">
        <button class="btn btn-outline-secondary" type="submit" id="button-addon2">
          <i class="bi bi-search" style="width: 16px; height: 16px;"></i>
        </button>
        </span>
      </form>
    </div>
  </section>

  
</div>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <section class=" w-100" style="height: fit-content;">
    <!-- 表格面板 -->
    <div class="d-flex justify-content-left" style="
      width: 100%;
      height: 100%;
      overflow: scroll;
      border-spacing: 0;
      word-wrap:break-all;
      word-break:break-all;
      table-layout:fixed;
    ">
      <!-- <table class="table" style="word-wrap:break-all; word-break:break-all; table-layout:fixed;"> -->
      <table class="table table-hover" style="height: 20rem;">
        <caption>当前搜索：{{ search_data }}</caption>
        <thead class="table-light">
          <tr>
            <th>ID</th>
            <th>中文</th>
            <th>法语</th>
            <th>类似表达</th>
            <th>来源</th>
            <th>定义</th>
            <th>例句</th>
            <th>分类</th>
            <th>标签</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody style="white-space: nowrap; overflow: hidden;">
        {% for obj in data_table %}
          <tr>
            <th scope="row">{{ obj.id }}</th>
            <td>{{ obj.chinese }}</td>
            <td>{{ obj.french }}</td>
            <td>{{ obj.similar }}</td>
            <td>{{ obj.source }}</td>
            <td>{{ obj.definition }}</td>
            <td>{{ obj.example }}</td>
            <td>{{ obj.get_cata_display }}</td>
            <td>{{ obj.tag }}</td>
            <!-- <td>******</td> -->
            <td>
                <a class="btn btn-outline-primary btn-sm" href="/term/{{ obj.id }}/edit/">编辑</a>
                <a class="btn btn-danger btn-sm" href="/term/{{ obj.id }}/delete/">删除</a>
                
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </section>

  
</div>
<!-- 分页组件 -->
<section class="p-3 d-flex justify-content-center">
  <nav aria-label="Page navigation">
  <ul class="pagination">
    {{ page_string }}
  </ul>
</nav>
</section>


  {% endblock %}

  {% block js %}
  

 


                                    
            
</script>
  {% endblock %}